language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

cache:
  directories:
     - node_modules

dist: trusty
addons:
  chrome: stable

install:
  - npm install

script:
  - ng lint --format stylish
  - ng test --watch false --single-run true --browsers ChromeHeadless
  - ng build --prod

deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN # Set in travis-ci.org dashboard

notifications:
  email:
    on_failure: change
    on_success: change
