language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

cache:
  directories:
     - ./node_modules

install:
  # - npm install -g @angular/cli
  - npm install

script:
  - ng lint
  - ng test --watch false
  - ng build --prod

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN # Set in travis-ci.org dashboard

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

# notifications:
#   email:
#     on_failure: change
#     on_success: change
